
services:
  react-dev:
    build:
      context: .
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
